### ISSUE TITLE
Rename '3'

### ISSUE THREAD

**Issue by Fweeb** [artistCDMJ/paint_artist_panel#1]
It's probably a good idea to rename your `3` file with something a bit more clear... and with the `.py` extension. I might suggest `artist_panel.py`.

**Comment by artistCDMJ** [comment]
thanks - still getting the hang of this interface

**Comment by artistCDMJ** [comment]
still lost - naming is borked in that I started with the paint_artist_panel.py and the rev4 now seems liek that is all the name is. I'm lost.

**Comment by Fweeb** [comment]
Ah... I see the issue. You named the git project (which lives in a folder) what you meant to name the actual file. You should be able to do a `git mv rev4.py paint_artist_panel.py` and then commit that. Then, you just edit that file. Git tracks the changes for you.

**Comment by artistCDMJ** [comment]
Okay, I will see what I can do. Kinda new at this, but I'll get it.

On Sun, Jan 17, 2016 at 9:12 PM, Jason van Gumster <notifications@github.com

**Comment by artistCDMJ** [comment]
Finally realized I could delete files and reload corrected ones. I hope that is fixed now.
